name: Instabot Deployment

on:
    push:
        branches:
            - main
    release:
        types: [ published ]

jobs:
    deploy:
#        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        environment: production
        steps:
            -   uses: actions/checkout@v4
            -   name: Deploy to Server
                run: |
                    echo "Deploying to server"
                    echo "host name is : ${{ secrets.REMOTE_HOST }}"
                    echo "Deployed to server"
#                uses: easingthemes/ssh-deploy@main
#                with:
#                    SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#                    ARGS: "-rlgoDzvc -i --delete"
#                    REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#                    REMOTE_USER: ${{ secrets.REMOTE_USER }}
#                    TARGET: ${{ secrets.REMOTE_TARGET }}
#                    EXCLUDE: "/dist/, /node_modules/, /vendor/, /var/"
#                    SCRIPT_AFTER: |
#                        whoami
#                        ls -al
#                        echo $RSYNC_STDOUT
